// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FAwo2Oa1-_Q_Q2t0PkbTrI5CJRQL29U',
    appId: '1:339590723702:web:4e4932c8e924a3aadb4757',
    messagingSenderId: '339590723702',
    projectId: 'fireloginapp-e34a0',
    authDomain: 'fireloginapp-e34a0.firebaseapp.com',
    storageBucket: 'fireloginapp-e34a0.appspot.com',
    measurementId: 'G-PV53E2ZZ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADX-UG31Y2wP2a9-fO_SMl58jWPniaoMc',
    appId: '1:339590723702:android:34ab224128b3ffe4db4757',
    messagingSenderId: '339590723702',
    projectId: 'fireloginapp-e34a0',
    storageBucket: 'fireloginapp-e34a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcoaxsnG7N0nO7_C4eq9icsVLI-wrLlfg',
    appId: '1:339590723702:ios:40d7174ff361ebffdb4757',
    messagingSenderId: '339590723702',
    projectId: 'fireloginapp-e34a0',
    storageBucket: 'fireloginapp-e34a0.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcoaxsnG7N0nO7_C4eq9icsVLI-wrLlfg',
    appId: '1:339590723702:ios:40d7174ff361ebffdb4757',
    messagingSenderId: '339590723702',
    projectId: 'fireloginapp-e34a0',
    storageBucket: 'fireloginapp-e34a0.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0FAwo2Oa1-_Q_Q2t0PkbTrI5CJRQL29U',
    appId: '1:339590723702:web:47591c52e98b308adb4757',
    messagingSenderId: '339590723702',
    projectId: 'fireloginapp-e34a0',
    authDomain: 'fireloginapp-e34a0.firebaseapp.com',
    storageBucket: 'fireloginapp-e34a0.appspot.com',
    measurementId: 'G-CEQEJ1VXL5',
  );
}
